_extends: .github
repository:
  name: octokit-auth-netrc
  description: netrc auth plugin for Octokit
  homepage: https://npm.im/octokit-auth-netrc
  private: false
branches:
  - name: master
    protection: null
rulesets:
  - name: prevent destruction of the default branch
    target: branch
    enforcement: active
    conditions:
      ref_name:
        include:
          - ~DEFAULT_BRANCH
        exclude: []
    rules:
      - type: deletion
      - type: non_fast_forward
