extends:
  - '@travi'
  - '@travi/mocha'
  - '@travi/cucumber'

rules:
  import/extensions:
    - error
    - ignorePackages

overrides:
  - files: example.js
    rules:
      import/no-extraneous-dependencies: off
