name: Node.js CI
'on':
  push:
    branches:
      - master
      - beta
      - renovate/**
  pull_request:
    types:
      - opened
      - synchronize
env:
  FORCE_COLOR: 1
  NPM_CONFIG_COLOR: always
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          cache: npm
      - run: npm clean-install
      - run: NODE_OPTIONS=--no-experimental-fetch npm test
      - uses: codecov/codecov-action@v3
  verify-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 14.15.0
          - 16.0.0
          - 16
          - 18
        include:
          - node: 18
            options: '--no-experimental-fetch'
    steps:
      - uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: ${{ matrix.node }}
      - run: npm clean-install
      - run: NODE_OPTIONS="${{ matrix.options }}" npm test
  release:
    needs:
      - verify
      - verify-matrix
    uses: form8ion/.github/.github/workflows/release-package.yml@master
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
